[tools]
bun = "1.2"
python = "3.13"

[env]
_.python.venv = { path = ".venv", create = true }
_.path = [
    "./mise-tasks",
    "{{config_root}}/node_modules/.bin"
  ]
_.file = ".env"
ASSETS_DIR = "{{config_root}}/assets"
TEMPLATES_DIR = "{{config_root}}/templates"
TMP_DIR = "{{config_root}}/tmp"
SCORES_DIR = "{{env.HOME}}/Documents/MuseScore4/Scores"
BOOK_PDF = "{{env.HOME}}/Documents/Music/Piano Sheet Music.pdf"
# Destination dir for add-cover-page
COVERED_DEST_DIR = "{{env.HOME}}/Documents/Music/Piano Sheet Music" 


[tasks.create-folder-toc]
description = "Create PDF with ToC"
run = "bun run src/create_folder_toc.ts"
